services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: "${GIT_COMMIT:-unknown}"
    platform: linux/amd64
    restart: unless-stopped

  nginx:
    image: nginx:1.28.0-alpine
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U appuser -d appdb -c 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Install vim as default editor
    command: >-
      bash -c "
      apk add --no-cache vim &&
      docker-entrypoint.sh postgres"
    restart: unless-stopped

  backups:
    image: postgres:17.4-alpine
    platform: linux/amd64
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    volumes:
      - ./cronjobs/backup.sh:/etc/periodic/daily/backup.sh
      - backup-data:/backups
    command: crond -f
    restart: unless-stopped

volumes:
  postgres-data:
  backup-data:
