services:
  app:
    build:
      context: .
      args:
        GIT_COMMIT: "${GIT_COMMIT:-unknown}"
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.28.0-alpine
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U appuser -d appdb -c 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Install vim as default editor
    command: >
      sh -c "apk add --no-cache vim &&
             docker-entrypoint.sh postgres"
    restart: unless-stopped

  backups:
    image: postgres:17.4-alpine
    platform: linux/amd64
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      ACCESS_KEY: $ACCESS_KEY
      SECRET_KEY: $SECRET_KEY
    volumes:
      - ./cronjobs/backup.sh:/etc/periodic/daily/01-backup
      - ./cronjobs/upload.sh:/etc/periodic/daily/02-upload
      - backup-data:/backups
    command: >
      sh -c "apk add --no-cache curl openssl file coreutils &&
             chmod u+x /etc/periodic/daily/01-backup &&
             chmod u+x /etc/periodic/daily/02-upload &&
             crond -f"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-data:
  backup-data:
